# Collector specific configuration
countries_filename: "Adm0Code.csv"
indicators_url: "https://vam.wfp.org/mvam_monitoring/mvam_dictionary.xlsx"
mvam_url: "https://vam.wfp.org/mvam_monitoring/api.aspx"
showcase_url: "https://vam.wfp.org/CountryPage_assessments.aspx?iso3=%s"
